### ISSUE TITLE
Double-check data types in CPR data.

### ISSUE THREAD

**Issue by iangow** [mccgr/cpr#3]
This builds on #1.

Looking [here](http://lib.law.virginia.edu/Garrett/corporate-prosecution-registry/browse/data-dictionary.txt), I see that `FINANCIAL_INSTITUTION` is a `Y/N` variable. This should probably be coded as boolean in PostgreSQL (by running `fix_boolean` when importing the data), but isn't.

I guess we should check the cases where it is `2` rather than `Yes` or `No`.

``` r
Sys.setenv(PGHOST = "10.101.13.99", PGDATABASE="crsp")
library(RPostgreSQL)
#> Loading required package: DBI
library(dplyr, warn.conflicts = FALSE)

pg <- dbConnect(PostgreSQL())

cpr_data <- tbl(pg, sql("SELECT * FROM cpr.cpr_data"))
cpr_data %>% count(financial_institution)
#> # Source:   lazy query [?? x 2]
#> # Database: postgres 9.6.4 [igow@10.101.13.99:5432/crsp]
#>   financial_institution     n
#>                   <chr> <dbl>
#> 1                  <NA>   120
#> 2                   Yes   175
#> 3                     2     5
#> 4                    No  2742

dbDisconnect(pg)
#> [1] TRUE
```

We should probably look [here](http://lib.law.virginia.edu/Garrett/corporate-prosecution-registry/browse/data-dictionary.txt) quite closely to see if any other variables might need special handling.

**Comment by bhaskarv9** [comment]
I am unable to connect to the “crsp” database. Do you think there is an access rights problem?  I get an error message when I run the pg <- dbConnect(PostgreSQL()) line.

Also I tried to push the changes to the code via Sourcetree but I am getting an error message. There are some pull requests that need to be completed. I get an error message when I pull requests as well.  Should I merge the staged files and then try to pull them ?

And I push the requests after I pull them .

**Comment by iangow** [comment]
> I am unable to connect to the “crsp” database. Do you think there is an access rights problem?  I get an error message when I run the pg <- dbConnect(PostgreSQL()) line.

Didn't we sort this out in #2?

> Also I tried to push the changes to the code via Sourcetree but I am getting an error message. There are some pull requests that need to be completed. I get an error message when I pull requests as well.  Should I merge the staged files and then try to pull them ?

You might have issues if you have changed the code and I have changed the code since you pulled it from GitHub. What you should probably do is:
 - *stash* your edits (if you haven't already committed them).
 - *pull* the latest code from GitHub, but making sure to select "rebase instead of merge" (see below).
- *apply* your stashed changes (you can do this from the "stashes" in the pane on the left of SourceTree.

<img width="614" alt="rebase" src="https://user-images.githubusercontent.com/1708790/29755780-588f359c-8be0-11e7-985e-5ee052fcdef8.png">

If you have already committed changes, then you might get merge conflicts at the second step. You might also get them at the third step (applying stash). I can help you if you encounter these.

> And I push the requests after I pull them.

Not sure what you mean here.

**Comment by bhaskarv9** [comment]
When I am trying to stash the edits I get a message saying that merging is necessary.


What I  mean when I say “And I push the requests after I pull them “ is that I do the push after I pull

**Comment by iangow** [comment]
@oliviajren 

I am not sure where this issue was left at. Not a high priority. I can explain better when you get to it.

**Comment by oliviajren** [comment]
A course I did before in Coursera might be helpful for the previous discussion regarding the version control. The course is called ["Version Control with Git"](https://www.coursera.org/learn/version-control-with-git/home/welcome) and is free if we don't need the certification at the end.

**Comment by iangow** [comment]
Don't worry about the discussion about version control above. We just need to check that the data that we're importing has the correct data type for each column. I think this means running the import code and inspecting the data.
