### ISSUE TITLE
Special decket_no observation 

### ISSUE THREAD

**Issue by oliviajren** [mccgr/cpr#6]
Figure out why in variable `docket_no`, a company's record as `1/19/1900`, while others are all numbers.

**Comment by oliviajren** [comment]
This is for a company called `Marubeni Corp`. As shown in the document provided [here](http://lib.law.virginia.edu/Garrett/corporate-prosecution-registry/detail_files/2630.html) for this company, the `Number on docket where judgment occurs` is shown as `1/19/1900`. Hence, I believe this is from their original docket source. We might need to contact them and ask whether if this is a typo there. But they also put a note on the same page saying - "The docket above is unofficial and may be incomplete or out-of-date. The official docket is available on [PACER ](https://www.pacer.gov)(fees may apply)."

**Comment by iangow** [comment]
Good enough. Thanks. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
