### ISSUE TITLE
Documentation for cpr

### ISSUE THREAD

**Issue by oliviajren** [mccgr/cpr#7]
A README.md file for cpr.

**Comment by iangow** [comment]
Should be `readme.md` to render correctly. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by oliviajren** [comment]
@iangow 
I'm trying to come up with dictionary for cpr using the following codes:
```ruby
library(tidyverse)

fix_names <- function(df) {
        names(df) <- gsub("\\s", "_", names(df))
        names(df) <- tolower(names(df))
        df
}



dictionary_cpr <- read_csv(file.path("http://lib.law.virginia.edu/Garrett",
                                 "corporate-prosecution-registry/browse",
                                 "data-dictionary.txt")) %>% 
        fix_names() %>% 
        separate(col = data_dictionary, 
                 into = c("variable_name", "note"), 
                 sep = "\\-") 
```
I'm just wondering is there any way to remove quotes("") in this table?

**Comment by iangow** [comment]
You probably need to remove the quotes (e.g., using `stringr::str_replace`) *before* `separate`-ing the data.

But in this case, this may all be more effort than it's worth. I think just linking to the underlying `.txt` in the `readme.md` might be enough.
